# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: copy file via ssh key
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          source: "src,target"
          target: "~/deploy/${{ github.repository }}/${{ github.run_number }}"

      - name: run remote shells
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER}}
          key: ${{ secrets.KEY }}
          script: |
            cd ~/deploy/${{ github.repository }}/${{ github.run_number }}
            chmod +x deploy/deploy.sh
            app_name=`basename ${{ github.repository }}`
            deploy/deploy.sh ${app_name} test ${{ secrets.PORT}} ${{ github.sha }} ./src
            rm -rf ~/deploy/${{ github.repository }}/${{ github.run_number }}
      - name: notify
        uses: foxundermoon/feishu-action@v2
        with:
          url: ${{ secrets.FEISHU_BOT_WEBHOOK_URL }}
          msg_type: text
          content: |
            text: |
              发布完成
              from github action
              repository: ${{ github.repository }}
              committer: ${{ github.actor }}
              compare: ${{ github.event.compare }}
              job status: ${{ job.status }}